# Generated by Django 2.2.3 on 2020-06-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200611_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
