# Generated by Django 2.2.3 on 2020-06-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='where',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
