# Generated by Django 2.2.3 on 2020-06-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_car', models.CharField(choices=[('evakuator', 'Evakuator')], max_length=255)),
                ('person', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=25)),
                ('phone2', models.CharField(max_length=25)),
                ('phone3', models.CharField(max_length=25)),
                ('no', models.CharField(max_length=15)),
                ('evakuator_type', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('length', models.CharField(max_length=255)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.Car_Model')),
            ],
        ),
        migrations.AddField(
            model_name='car_model',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Make'),
        ),
    ]
